### ISSUE TITLE
Header Text Misbehaving on PrimoVE 

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/primo-explore-devenv#25]
All kinds of HTML and CSS issues are causing the "Galter Health Sciences Library & Learning Center" text/link in the header to throw the appearance all over the place. 

- [x] **On medium widths, the text hides behind the search field**
<img width="904" alt="Screen Shot 2021-04-19 at 3 57 53 PM" src="https://user-images.githubusercontent.com/8138663/115295562-e1431b00-a127-11eb-84e1-95b8c2a6de25.png">

- [x] **On mobile, text is cut off**
<img width="583" alt="Screen Shot 2021-04-19 at 3 58 06 PM" src="https://user-images.githubusercontent.com/8138663/115295588-ea33ec80-a127-11eb-9d99-a28b4f0d8d62.png">

- [x] **On linkresolver pages, text appears outside of header and behind text** [example result](https://search.library.northwestern.edu/discovery/openurl?institution=01NWU_INST&vid=01NWU_INST:HSLV&id=pmid:28655517&sid=Entrez:PubMed)
<img width="1430" alt="Screen Shot 2021-04-19 at 3 57 11 PM" src="https://user-images.githubusercontent.com/8138663/115295608-f15afa80-a127-11eb-97a7-7d71237fa620.png">

(Transferred from galter-website)

**Comment by jpastva** [comment]
I also just noted some weird header behavior when using the E-journals search page

![image](https://user-images.githubusercontent.com/9001461/128415872-dccf706a-f803-4a99-82df-e03197632b96.png)

**Comment by Meowcenary** [comment]
> I also just noted some weird header behavior when using the E-journals search page
> 
> ![image](https://user-images.githubusercontent.com/9001461/128415872-dccf706a-f803-4a99-82df-e03197632b96.png)

This is resolved now thankfully. I'm looking into the other styling issues.

**Comment by Meowcenary** [comment]
Some documentation that might be helpful on this: https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/030Primo_VE_User_Interface/010Primo_VE_Customization_-_Best_Practices
